### ISSUE TITLE
Wait, why?

### ISSUE THREAD

**Issue by maclanegamer** [nuxlar/UmbralMithrix#12]
Why did you revert to 1.8.8?

**Comment by Darkmega18** [comment]
I think it might've been my fault complaining about being unable to choose umbral or not and until they find out how they can blacklist all the things so I don't get bodied by extremely buffed pizza's while having base movement speed after my items get sucked cause modded gear. :V

**Comment by nuxlar** [comment]
it's because i don't want to work on the mod anymore
