### ISSUE TITLE
[Feature Request] Umbral Shrine/Gate (Activate Umbral Mod In-Game)

### ISSUE THREAD

**Issue by acanthii** [nuxlar/UmbralMithrix#13]
I love this mod but sometimes I'd like to run the Mithrix fight normally, and it's inconvenient to open r2modman every time I want to switch between vanilla behaviour and vanilla behaviour

I propose the idea of having an Umbral Gate or Umbral Shrine in commencement that changes the fight from regular Mithrix to Umbral Mithrix per-run!

Thanks :)

**Comment by acanthii** [comment]
Sorry, for a sec I thought I was being stupid after seeing the feature in a old video, and just thought I didn't check the configs, but no it's not an option there either hahah

I'd love to see a return of this feature from before 2.0, but if that's not planned that's alright ;)

**Comment by Nuxlar** [comment]
That feature was mainly made because umbral 1.0 was pretty unfair and had a lot less code to worry about. Might try and re-implement it if the recent Gearbox update doesnt completely kill the game.

**Comment by Nuxlar** [comment]
No longer working/maintaining the mod, so this likely won't happen soon if ever. Maintained version here https://thunderstore.io/package/Goorakh/UmbralMithrixFork/

**Comment by RondoRevolution** [comment]
Any chance of this being added now that you're back at maintaining the mod? Would love to keep the mod enabled and be able to choose when I want to fight Umbral Mithrix or Vanilla Mithrix.

**Comment by Nuxlar** [comment]
Nope, it'd be a lot of extra work and testing, like I said it was only a feature in the first place because of 1.0 being too difficult gameplay wise.
