### ISSUE TITLE
immunity bug?

### ISSUE THREAD

**Issue by Cominfiniti** [nuxlar/UmbralMithrix#14]
I turned on practice mode to see what movesets he has but upon reaching his phase 3 his immune frame is...inf? or am I missing something?

**Comment by Cominfiniti** [comment]
here's a screenshot for closer look 
![image](https://github.com/nuxlar/UmbralMithrix/assets/131906409/8661ba5e-cd7a-42eb-b642-b3381041103d)

**Comment by nuxlar** [comment]
Currently there's an issue with moonstorm/starstorm that causes this, will try and fix on my end at some point

**Comment by Hevia** [comment]
We encountered this on phase 2. I dont recall being in practice mode unless one of the players I was with triggered it and I didn't notice. I do have SS2/MSU installed. 

Lmk if you want a log

**Comment by nuxlar** [comment]
the incompatibility should be fixed now, please open another issue with a log if something still comes up. Thanks for letting me know y'all
