### ISSUE TITLE
second phase bugged, semi-softlocked run

### ISSUE THREAD

**Issue by kaden0823** [nuxlar/UmbralMithrix#14]
[LogOutput.log](https://github.com/user-attachments/files/16939266/LogOutput.log)
second phase glitched, main mithrix became invulnerable permanently(killing doppelganger did nothing), thus softlocking my run

**Comment by kaden0823** [comment]
update, after using a bug with a modded survivor's moveset to clip outside of the arena, after a time, main mithrix died on its own and phase-transitioned as normal.

**Comment by Nuxlar** [comment]
make sure you're running mods updated for SOTS, Resonance Field Generator seems to be constantly throwing errors
