### ISSUE TITLE
Umbral Mithrix, plus many many other mods, seem to be causing a really bad error where you *cannot respawn*

### ISSUE THREAD

**Issue by FoxxyFerris** [nuxlar/UmbralMithrix#15]
![image](https://github.com/user-attachments/assets/213d1812-276d-4390-a9bd-9289c547b59f)
while the image itself does not have Umbral Mithrix in the log itself (as i had disabled it beforehand to test if that would fix it) it is still erroring out even with the mod enabled. Any idea for a fix?

**Comment by Nuxlar** [comment]
use mods updated for sots
