### ISSUE TITLE
Is there no way to fight normal mithrix if the mod is enabled?

### ISSUE THREAD

**Issue by myadyth** [nuxlar/UmbralMithrix#16]
Before, if I wanted to play 2 runs and have one of them be an umbral run, I would just decide to hit the pillar. Now, the mod seems to permanently change mithrix to umbral mithrix. 

Is there any way that I simply don't see to fight normal mithrix without having to unload, disable the mod, and reload the game?

**Comment by nuxlar** [comment]
yep there was a big update, you should probably read the modpage. The obelisk was removed and umbral is always active.

**Comment by myadyth** [comment]
Would it be possible to have normal mithrix still be accessible for quality-of-life?
