### ISSUE TITLE
 AltMithrixTheme Mod No Longer Works

### ISSUE THREAD

**Issue by BobRossThy3rd** [nuxlar/UmbralMithrix#16]
I know this isn't technically you're problem since this is a side mod, not the main mod but whenever the Mithrix fight begins while using the alternate music mod no music what so ever plays. This happens regardless of ithe Umbral Mithrix mod being used or not (i,e, fighting vanilla Mithrix). I have faced this issue along with a friend of mine. It is likely a result of the new DLC as even with the alt music mod being the only mod used no audio is played for the fight theme. It's not a major issue because the normal music still works just fine if the alternate is turned off, but still it's a little disappointing.

**Comment by Nuxlar** [comment]
Broke with SOTS, I don't have the audio project anymore nor am I modding anymore so it won't be updated for the foreseeable future
