### ISSUE TITLE
Add the ability to tweak phase 4 only

### ISSUE THREAD

**Issue by XayahNeko** [nuxlar/UmbralMithrix#17]
I love the modified bossfight, but phase 4 is a extreme difficutly spike that is just not fun for my friendgroup when we are running umbral mithrix. Is there any chance you could make a 'alterntive version' (that is just a buffed stats verison of phase default, or the ability to nerf phase 4 directly without nerfing the rest of the boss like you can nerf phase 3.

**Comment by Nuxlar** [comment]
you can deactivate phase 4 completely in the config, I'm also not maintaining the mod anymore, here's the latest one https://thunderstore.io/package/Goorakh/UmbralMithrixFork/
