### ISSUE TITLE
Can't move or do anything when UmbralMithrix used with character mods

### ISSUE THREAD

**Issue by NU8B** [nuxlar/UmbralMithrix#18]
[LogOutput.log](https://github.com/user-attachments/files/18094510/LogOutput.log)
As soon as I press start, and loads in the map, I will keep getting the same error like the one at the bottom of the log file. Very frequently.
```
[Error  : Unity Log] MissingMethodException: Method not found: void RoR2.Projectile.ProjectileManager.FireProjectile(UnityEngine.GameObject,UnityEngine.Vector3,UnityEngine.Quaternion,UnityEngine.GameObject,single,single,bool,RoR2.DamageColorIndex,UnityEngine.GameObject,single)
Stack trace:
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.CharacterBody::AddTimedBuff>?974149636(RoR2.CharacterBody,RoR2.BuffDef,single)
EntityStates.SpawnTeleporterState.OnExit () (at <a43009bc6a5f4aee99e5521ef176a18d>:IL_004F)
RoR2.EntityStateMachine.SetState (EntityStates.EntityState newState) (at <a43009bc6a5f4aee99e5521ef176a18d>:IL_004A)
RoR2.EntityStateMachine.TryStateTransition () (at <a43009bc6a5f4aee99e5521ef176a18d>:IL_0008)
RoR2.EntityStateMachine.ManagedFixedUpdate (System.Single deltaTime) (at <a43009bc6a5f4aee99e5521ef176a18d>:IL_0011)
RoR2.EntityStateMachine.FixedUpdate () (at <a43009bc6a5f4aee99e5521ef176a18d>:IL_0006)
```
And I won't be able to move or do anything. This applies to all characters, not just modded ones. As long as I have a modded character downloaded, I will get this bug.

In this log I used it with lots of mods, just because I don't have my old profile anymore. But even when used with a single modded character, I will get this same error. I don't have any dlc in case that matters.

I used to be able to use it when I didn't use character mods yet.
Now I have to choose between modded characters or UmbralMithrix which is something I don't wanna do ToT.

I'd appreciate if you could look into this. looking forward to trying out your mod thanks!

**Comment by NU8B** [comment]
Ok I thought it was because I added character mods. Cus it was still working the other day. I just tried with only the UmbralMithrix  mod and still got the same error. 

Probably because of game update, my bad.

**Comment by nmurphy101** [comment]
same can't move after landing after starting as well @Nuxlar

**Comment by Nuxlar** [comment]
broken because of the updates most likely, Goorakh is now maintaining the mod, I updated my mod to just download theirs but here's the link just in case. I'm not working on mods for the time being. https://thunderstore.io/package/Goorakh/UmbralMithrixFork/
