### ISSUE TITLE
Phase 3 very bugged

### ISSUE THREAD

**Issue by Turbler4** [nuxlar/UmbralMithrix#2]
Seems with my mods (starstorm 2 included) phase 3 refuses to spawn the crystals, but an interesting interaction with the sawmerang allows me to damage him a little bit and after about 1/4 of his health is down the crystals will spawn. However, the last crystal will not die and the fight cannot progress.

I've included a log file and a video.
[zipped_log.zip](https://github.com/FocusedFault/UmbralMithrix/files/12781066/zipped_log.zip)
https://www.youtube.com/watch?v=V-BRHqNH_xs

**Comment by Nuxlar** [comment]
did inferno add mithrix mod compatibility? because that one changes the fight as well so issues are to be expected with that. Also he it looked like the immunity was removed though the crystal didnt physically get destroyed

**Comment by Turbler4** [comment]
I have the inferno mithrix changes disabled in the config unless it still causes an issue anyway. I've only seen saw do any damage to him during immunity, he is still immune after I destroy the last crystal. My shots are not dealing damage to him.

**Comment by Guilhem30** [comment]
I experienced the same bug but i don't have the inferno mod. I tried to restart the map 3 times with the propersave mod but Mithrix got stuck in invincible mode every time

**Comment by Nuxlar** [comment]
Hopefully fixed with the new update, if the issue persists post the bug in Moonstorm's repo (something with buff switching)
