### ISSUE TITLE
Phase 3 Bug

### ISSUE THREAD

**Issue by b3atz** [nuxlar/UmbralMithrix#3]
Running 2.1.2
Phase 3 started and could not dmg him from the start.
Did another run in practice mode with Starstrom 2 and DLC toggled off and was able to fight him no problem (was able to dmg him at the start of phase 3 then he spawned in clones shortly.
[log-output.txt](https://github.com/FocusedFault/UmbralMithrix/files/13211409/log-output.txt)
after). 
[log-fight-output.txt.txt](https://github.com/FocusedFault/UmbralMithrix/files/13211464/log-fight-output.txt.txt) <- logoutput from the bugged fight

**Comment by Nuxlar** [comment]
Idk what else I can do on my end to fix it unfortunately, open an issue on Moonstorm's repo if there isn't one already open
