### ISSUE TITLE
Unusual phase 3 mercenary dash issue

### ISSUE THREAD

**Issue by shyg4l** [nuxlar/UmbralMithrix#6]
This specific thing has happened twice now and it appears to be tied to dashing into both the clone and mithrix at once specifically at a downward angle
It causes a cartoonish frame drop and the only way i've been able to fix it is by force killing mithrix

https://youtu.be/keyM9pK6sLM?si=5lkK-4GD13kLZ2Cy 
(sorry for the youtube video the file was too chunky and it wouldnt let me attach the file it in this description :( )

**Comment by shyg4l** [comment]
i was told this issue was linked to cloudburst, i turned that off, then it started happening with classes that use melee attacks in general
on paladin it even hard crashed outright

**Comment by Nuxlar** [comment]
should be fixed with the latest update
