### ISSUE TITLE
Trophy appearing in BetterMoonPilliars potential drop

### ISSUE THREAD

**Issue by shyg4l** [nuxlar/UmbralMithrix#7]
self explanatory
![Screenshot 2023-11-05 003729](https://github.com/FocusedFault/UmbralMithrix/assets/149918826/0d6c43eb-a1ea-49b4-a34d-0149d3898c81)

**Comment by Nuxlar** [comment]
hm i thought i removed it from everything, might or might not get around to it soon

**Comment by Nuxlar** [comment]
fixed with the latest update
