### ISSUE TITLE
Mithrix Seamless Spawning(?)

### ISSUE THREAD

**Issue by SOMSTATE** [nuxlar/UmbralMithrix#8]
Replacing the spawn orb for Mithrix in the center of the arena with his spawn pose. Unsure if possible, if not, replacing the slamming sound from him spawning with teleporting or Umbra SFX, since he doesn't drop down anymore.

**Comment by nuxlar** [comment]
if you mean make Mithrix in his throne sitting in the middle without the orb then technically it's possible but its a lot of work for nothing. I could change the sound as well but that would also be a lot of work for nothing. The sound can be interpreted as the orb "popping" and the orb covers mithrix magically appearing in the chair. So it's pretty seamless as is
