### ISSUE TITLE
Phase 3 crash bug

### ISSUE THREAD

**Issue by spjderr** [nuxlar/UmbralMithrix#8]
Looks like mithrix takes hits from stuff multiple times it happens here with voidsent flame but also happens on other characters with captains diablo strike or artificers m1.

log file https://drive.google.com/file/d/1nHdAHoN_IRpmHcN1eb0xpq0UPM6Bi47Y/view?usp=drive_link
video https://medal.tv/games/ror-2/clips/1CCwXCRTflCsCR/d1337CPDiBXG?invite=cr-MSx2WGIsMTI2MDA3NDcs

**Comment by Nuxlar** [comment]
should be fixed with the latest update
