### ISSUE TITLE
How am I meant to dodge a directly centered on top of me pizza without gear...?

### ISSUE THREAD

**Issue by Darkmega18** [nuxlar/UmbralMithrix#9]
So I thought mithrix was meant to spawn normally unless I hit the obelisk so I didn't even realize that a recent update did away with that entirely, and nor did I notice a lack of obelisk when I swung past to try to flatten him with Handy just now... to my dismay umbral was on cause I thought I had to choose to fight the strong one and I did manage to get him down but not before he sucked all my items and made me impossibly slow and then spawned a basically undodgeable pizza right on top of me. So with all my gear gone I got juggled, slowed to an even further crawl then murdered several seconds into the survival phase.

changelog says I'm meant to get some speed items left over but it didn't seem like I got any. unless the modded items he stole are the reason I got slowed so badly? the only thing that was left in my inventory on death was some shadow summoning ring I got from rally point delta and nemesis commando's soul. >_<

Is the only way to not fight umbral to know that I'm not gonna fight umbral before hand and not install the mod? :V cause I judge if I can take umbral based on my gear or if I need to finish a challenge or something. so it was good being able to not always have him be op.

**Comment by nuxlar** [comment]
You can download an older version of the fight if that's the one you preferred, 1.8.8 is probably the most recent stable one with the features you want. Also its most likely the modded items since they wouldnt be blacklisted from Mithrix.

**Comment by Darkmega18** [comment]
ah frick. mod managers gonna be yelling at me constantly to update then. first world problems, I know. 

I guess I'll just go back to scrub mode for bosses while I'm hunting unlocks. >_>'

**Comment by nuxlar** [comment]
For now use the previous version that doesn't have the steal 1.8.8. I might change the way the blacklist works at some point to include modded items.

**Comment by Darkmega18** [comment]
alrighty then.
