### ISSUE TITLE
another phase 3 bug

### ISSUE THREAD

**Issue by shyg4l** [nuxlar/UmbralMithrix#9]
whenever i use arrow rain on real mithrix in phase 3 it does 1 of 2 things, often times both
it will either make him completely unhitable by huntress' abilities until the end of the phase, only able to be damaged by allies
or it will spike the lag so hard i literally hit a single frame a second
the second one is a greater issue i've noticed with multi hit abilities in general on phase 3

https://youtu.be/W0fjhzsswxk
(sorry for another youtube link again file was too big again :( )

**Comment by shyg4l** [comment]
happened again this time on sniper
https://youtu.be/hIWrAZx9Lks

**Comment by Nuxlar** [comment]
should be fixed with the latest update
